# Interesting link: https://binary-studio.com/blog/2021/12/21/lint-your-project-with-github-actions/

name: Lint
run-name: ${{ github.actor }} is linting node-red-contribu-arrowhead using GitHub Actions ğŸš€

on:
  push:
    branches: [main, master]

jobs:
  linting:
    name: Linting
    runs-on: self-hosted
    container:
      image: node:18
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint > lint.log

      - name: Archive lint artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint-artifact.log
          path: lint.log
          retention-days: 30

      - run: echo "ğŸ This job's status is ${{ job.status }}."
